# This is a config for E2B sandbox template.
# You can use template ID (o59va278o8abx49fz97r) or template name (vibe-nextjs-temp-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-temp-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-temp-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-temp-test-2')

team_id = "0d8c3bda-1251-423f-afa8-73827870b535"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-temp-test-2"
template_id = "o59va278o8abx49fz97r"
